### ISSUE TITLE
Incompatible project version

### ISSUE THREAD

**Issue by badruzeus** [linzhouyu/LegacyIONDRVSupport#1]
First, nice project!
But I got problem when opening the project using Xcode 8.2.1 under OS X El Capitan 10.11.6:
Failed to load project at '~/LegacyIONDRVSupport/LegacyIONDRVSupport.xcodeproj', incompatible project version.

Plz fix this issue, thanks.

**Comment by linuslin0** [comment]
Thank you. Just changed Xcode compatible version to 8.0. I use Xcode 10 beta + macOS 10.14 SDK to build this and the kext is only for macOS 10.14. However you could still build it with older Xcode and SDK.
